services:
  db:
    image: postgres:14.1-alpine
    container_name: db-fast-api
    environment:
      - POSTGRES_DB=fastapi_starterkit
      - POSTGRES_USER=fastapi_starterkit_user
      - POSTGRES_PASSWORD=1234
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-d", "fastapi_starterkit123", "-U", "fastapi_starterkit_user123" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis-fast-api
    image: redis:7.0.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: redis-server

  backend:
    container_name: backend-fast-api
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://fastapi_starterkit_user:1234@db-fast-api/fastapi_starterkit
      - REDIS_HOST=redis-fast-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/srv
    depends_on:
      redis:
          condition: service_started
      db:
          condition: service_healthy

    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000

volumes:
  pg-data:
  redis-data: