services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=fastapi_starterkit
      - POSTGRES_USER=fastapi_starterkit_user
      - POSTGRES_PASSWORD=1234
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    container_name: redis-fast-api
    image: redis:7.0.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    expose:
      - 6379
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: redis-server

volumes:
  pg-data:
  redis-data: