services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=fastapi_starterkit
      - POSTGRES_USER=fastapi_starterkit_user
      - POSTGRES_PASSWORD=1234
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg-data: